; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;   底座 board：Espressif ESP32-S3-DevKitC-1（官方板）
;   覆盖项：芯片为 ESP32-S3-FH4R2（4MB Flash + 2MB PSRAM + USB CDC）

[env:esp32-s3-fh4r2]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_echo = yes

; ============ 芯片特性覆盖 ============

board_build.partitions = min_spiffs.csv     ; 使用 min_spiffs.csv 分区表，保留Flash的大部分空间用于程序AB分区
board_upload.maximum_size = 4194304         ; 4 * 1024 * 1024
board_upload.flash_size = 4MB				; Flash 容量

; ============ build_flags ============

build_flags =
    -UARDUINO_USB_MODE	                    ; undefine 官方板的 USB_MODE
    -DARDUINO_USB_CDC_ON_BOOT=1             ; 启用 USB CDC 串口
    -DBOARD_HAS_PSRAM                       ; FH4R2 内置 2MB Octal PSRAM

	; NimBLE 默认 CCCD 订阅记录容量只有 8 条:目前3个输入报告 + 电池服务,
	; 每台主机占用 4 条,两台主机即到上限,
	; 触发 NimBLE 的 round-robin 溢出策略静默删除"最旧主机的配对记录"。
	; 提高容量,给多主机 + 反复订阅留足余量。
    -DCONFIG_BT_NIMBLE_MAX_CCCDS=32         ; 保留原项目的 NimBLE CCCD 配置


; === 依赖库，PlatformIO会联网下载这些库参与编译 ===
lib_deps =
	h2zero/NimBLE-Arduino@ 2.5.1
	ayushsharma82/ElegantOTA @ 3.1.7
	fastled/FastLED @ 3.10.3
	tanakamasayuki/TensorFlowLite_ESP32 @ 1.0.0
	invensenseinc/ICM42670P@ 1.0.9
	sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library@ 1.0.4
	esp32async/ESPAsyncWebServer @ 3.12.0
